CREATE DATABASE life;

CREATE USER jov WITH ENCRYPTED PASSWORD '1000';

GRANT ALL PRIVILEGES ON DATABASE life TO jov;

\c life

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO jov;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO jov;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO jov;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jov;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jov;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO jov;